@startuml

User -> Broker: Publish\n{\n  "msg": <Message>,\n  "target_queues": [\n    <Queue 1>,\n    <Queue 2>\n  ]\n}

loop Each target\nqueue

Broker -> "Data Store": Write message\nto queue

"Data Store" --> Broker: Success

end

Broker --> User: Success

@enduml
