@startuml

User -> Broker: Subscribe "client" to "queue" at index

Broker -> "Data Store": Does client exist?

alt Client exist

Broker -> "Data Store": Record associate of "client" to "queue"

"Data Store" -> Broker: Success

Broker -> "Data Store": Receive data stream from "queue" starting at index

== Message Streaming ==

loop Until User Stop Stream

"Data Store" --> Broker: Message ###

Broker --> User: Message ###

User -> Broker: ACK ###

Broker -> "Data Store": "client" received message ### from "queue"

end

== Stop Streaming ==

User -> Broker: Stop streaming "queue" to "client"

Broker -> "Data Store": Stop streaming "queue"

"Data Store" -> Broker: Success

Broker --> User: Success

== Retransmission ==

loop Until User Stop Stream

"Data Store" --> Broker: Message ###

Broker --> User: Message ###

Broker -> Broker: Timeout waiting for ACK

Broker --> User: Retransmit Message ###

end

else Client is unknown

Broker --> User: Client is unknown

end

@enduml
