# Copyright 2021-2022 The httpmq Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: CICD

on:
  workflow_dispatch:

jobs:
  cicd:
    runs-on: ubuntu-latest

    services:
      nats:
        image: nats:2.6.2-alpine
        ports:
          - 4222:4222
        options: --entrypoint="/nats-server --config /nats-server.conf --jetstream"

    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.29

      - name: Build
        run: go build -v -o httpmq.bin .

      - name: Test
        run: go test --count 1 -timeout 30s -short ./...
        env:
          NATS_HOST: nats
          NATS_PORT: ${{ job.services.redis.nats[4222] }}
